title: Greg Werner
description: > # this means to ignore newlines until "baseurl:"
  Greg Werner's personal site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jgwerner.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gwerner
github_username:  jgwerner

# Build settings
theme: jekyll-theme-minimal
